### ISSUE TITLE
Missing pid?

### ISSUE THREAD

**Issue by ericelliott** [iyshannon/cuid#1]
First, great work on this.

I just have one point of confusion. I don't see how your fingerprint function incorporates the pid. Am I missing something?

Actually, on further inspection, I see the Ruby docs say "Not available on all platforms." Maybe you can suggest a viable alternative for Ruby (I know very little about it). I don't think relying solely on the hostname length is strong enough.

~ Eric

**Comment by iyshannon** [comment]
Thanks for getting back to me.  

In Ruby, `$$` represents the current process ID, so in the get_fingerprint function, the return statement is calling format on the PID and calling format on the hostid and concatenating them.  

The hostid is calculated the same way your node version does it (I think): splitting the hostname into an array of characters, then calculating the sum of the ASCII value of each character, plus the length of the hostname, plus 36.  

I'll have a look and let you know what I find as far as what could be used in place of the process ID in case it isn't available in certain scenarios.

Ian

**Comment by ericelliott** [comment]
Ah, thanks for the response. Can you at least discover which platforms we're leaving high and dry when we use the PID in Ruby? If we're going to leave it, we should document the known issues.

**Comment by iyshannon** [comment]
Closing this - the platform availability issue in the documentation is in regards to starting a new process and accessing that process ID, not when getting Ruby's process ID which is the only thing we need.
